apiVersion: v1
kind: ReplicationController
metadata:
  name: php-fpm56
  labels:
    name: php-fpm

spec:
  replicas: 2
  selector:
    name: php-fpm
  template:
    metadata:
      labels:
        name: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: devel:5000/php56
        imagePullPolicy: IfNotPresent
        ports:
          - name: php-fpm
            containerPort: 9006
            #hostPort: 8081
        env:
          - name: fpm_port
            value: '9006'
