apiVersion: v1
kind: ReplicationController
metadata:
  name: php-fpm56-v2
  labels:
    name: php-fpm

spec:
  replicas: 2
  selector:
    name: php-fpm
    version: v2
  template:
    metadata:
      labels:
        name: php-fpm
        version: v2
    spec:
      volumes:
      - name: nfs
        nfs:
          server: nfs
          path: "/data/nfs"

      containers:
      - name: php-fpm
        image: devel:5000/php56
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: nfs
            mountPath: "/opt"
        ports:
          - name: php-fpm
            containerPort: 9006
            #hostPort: 8081
        env:
          - name: fpm_port
            value: '9006'
        resources:
          limits:
            cpu: 0.5
            memory: 512Mi
