apiVersion: v1
kind: Service
metadata:
  name: fpm-svc
  labels: 
    name: fpm-svc-labels

spec:
  selector:
    name: php-fpm
  ports:      
    - name: http
      port: 9000
      #targetPort: 8081
      #protocol: TCP
    #- port: 443
    #  name: https
    #  protocol: TCP
    #  targetPort: 30002
