---
kind: Service
apiVersion: v1
metadata:
  name: ng-cluster-svc
spec:
  selector:
    app: ng
  ports:
  - protocol: TCP
    port: 80
    #targetPort: 9376
    nodePort: 30062
  clusterIP: 10.254.254.253
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
