---
apiVersion: v1
kind: Service
metadata:
  name: ng-svc-cluster
spec:
  type: LoadBalancer
  clusterIP: 10.254.254.254
  selector:
    name: ng
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30061
    protocol: TCP
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.220

