apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-nfs-v1
  labels:
    name: nginx

spec:
  replicas: 2
  selector:
    name: ng
    version: v1
  template:
    metadata:
      labels:
        name: ng
        version: v1
    spec:
      volumes:
      - name: nfs
        nfs:
          server: 192.168.1.177
          path: "/data/nfs"

      containers:
      - name: nginx
        image: devel:5000/nginx:1.10.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: nfs
            mountPath: "/opt"
        ports:
          - name: http 
            containerPort: 80
            #hostPort: 8081
        env:
          - name: php_server
            value: fpm-svc
          - name: port
            value: '9006'
        #  - name: port
        #    value: '9006'
        resources:
          limits:
            cpu: 0.5
            memory: 384Mi
