apiVersion: v1
kind: Service
metadata:
  name: ng-svc
  labels: 
    name: ng-svc-labels

spec:
  type: LoadBalancer
  selector:
    name: ng
  ports:      
    - name: http
      port: 80
  status:
    loadBalancer:
      ingress:
        ip: 192.168.1.210
        #hostname: C153

      #targetPort: 8081
      #protocol: TCP
    #- port: 443
    #  name: https
    #  protocol: TCP
    #  targetPort: 30002
