apiVersion: v1
kind: Service
metadata:
  name: ng-svc
  labels: 
    name: ng-svc-labels

spec:
  selector:
    name: nginx
  ports:      
    - name: http
      port: 80
      #targetPort: 8081
      #protocol: TCP
    #- port: 443
    #  name: https
    #  protocol: TCP
    #  targetPort: 30002
